var namespace_w_s_m =
[
    [ "Utils", "namespace_w_s_m_1_1_utils.html", "namespace_w_s_m_1_1_utils" ],
    [ "AbstractLockGuard", "class_w_s_m_1_1_abstract_lock_guard.html", "class_w_s_m_1_1_abstract_lock_guard" ],
    [ "ATFCameraData", "struct_w_s_m_1_1_a_t_f_camera_data.html", "struct_w_s_m_1_1_a_t_f_camera_data" ],
    [ "Color", "class_w_s_m_1_1_color.html", "class_w_s_m_1_1_color" ],
    [ "CurveData", "struct_w_s_m_1_1_curve_data.html", "struct_w_s_m_1_1_curve_data" ],
    [ "EdgeData", "struct_w_s_m_1_1_edge_data.html", "struct_w_s_m_1_1_edge_data" ],
    [ "FaceData", "struct_w_s_m_1_1_face_data.html", "struct_w_s_m_1_1_face_data" ],
    [ "FacetsBodyData", "struct_w_s_m_1_1_facets_body_data.html", "struct_w_s_m_1_1_facets_body_data" ],
    [ "GroupInstancePath", "class_w_s_m_1_1_group_instance_path.html", "class_w_s_m_1_1_group_instance_path" ],
    [ "IGraphicsFactory", "class_w_s_m_1_1_i_graphics_factory.html", "class_w_s_m_1_1_i_graphics_factory" ],
    [ "ImageData", "struct_w_s_m_1_1_image_data.html", "struct_w_s_m_1_1_image_data" ],
    [ "IMarker", "class_w_s_m_1_1_i_marker.html", "class_w_s_m_1_1_i_marker" ],
    [ "InstanceData", "struct_w_s_m_1_1_instance_data.html", "struct_w_s_m_1_1_instance_data" ],
    [ "Interval2d", "class_w_s_m_1_1_interval2d.html", "class_w_s_m_1_1_interval2d" ],
    [ "Interval3d", "class_w_s_m_1_1_interval3d.html", "class_w_s_m_1_1_interval3d" ],
    [ "IPolygon", "class_w_s_m_1_1_i_polygon.html", "class_w_s_m_1_1_i_polygon" ],
    [ "IPolyLine", "class_w_s_m_1_1_i_poly_line.html", "class_w_s_m_1_1_i_poly_line" ],
    [ "IRayFireFilterAndAbort", "class_w_s_m_1_1_i_ray_fire_filter_and_abort.html", "class_w_s_m_1_1_i_ray_fire_filter_and_abort" ],
    [ "LayerData", "struct_w_s_m_1_1_layer_data.html", "struct_w_s_m_1_1_layer_data" ],
    [ "Line3d", "class_w_s_m_1_1_line3d.html", "class_w_s_m_1_1_line3d" ],
    [ "LoopData", "struct_w_s_m_1_1_loop_data.html", "struct_w_s_m_1_1_loop_data" ],
    [ "MaterialData", "struct_w_s_m_1_1_material_data.html", "struct_w_s_m_1_1_material_data" ],
    [ "MaterialProps", "class_w_s_m_1_1_material_props.html", "class_w_s_m_1_1_material_props" ],
    [ "ModelChangeData", "struct_w_s_m_1_1_model_change_data.html", "struct_w_s_m_1_1_model_change_data" ],
    [ "ObjectHistoryID", "class_w_s_m_1_1_object_history_i_d.html", "class_w_s_m_1_1_object_history_i_d" ],
    [ "Plane", "class_w_s_m_1_1_plane.html", "class_w_s_m_1_1_plane" ],
    [ "Point2d", "class_w_s_m_1_1_point2d.html", "class_w_s_m_1_1_point2d" ],
    [ "Point3d", "class_w_s_m_1_1_point3d.html", "class_w_s_m_1_1_point3d" ],
    [ "Result", "class_w_s_m_1_1_result.html", "class_w_s_m_1_1_result" ],
    [ "TextureData", "struct_w_s_m_1_1_texture_data.html", "struct_w_s_m_1_1_texture_data" ],
    [ "Transf3d", "class_w_s_m_1_1_transf3d.html", "class_w_s_m_1_1_transf3d" ],
    [ "UnitVector3d", "class_w_s_m_1_1_unit_vector3d.html", "class_w_s_m_1_1_unit_vector3d" ],
    [ "Vector2d", "class_w_s_m_1_1_vector2d.html", "class_w_s_m_1_1_vector2d" ],
    [ "Vector3d", "class_w_s_m_1_1_vector3d.html", "class_w_s_m_1_1_vector3d" ]
];