var annotated_dup =
[
    [ "FormIt", "namespace_form_it.html", [
      [ "AutoSave", "namespace_form_it_1_1_auto_save.html", [
        [ "Config", "struct_form_it_1_1_auto_save_1_1_config.html", "struct_form_it_1_1_auto_save_1_1_config" ]
      ] ],
      [ "Collaboration", "namespace_form_it_1_1_collaboration.html", [
        [ "ChatMessage", "struct_form_it_1_1_collaboration_1_1_chat_message.html", "struct_form_it_1_1_collaboration_1_1_chat_message" ],
        [ "UserInfo", "struct_form_it_1_1_collaboration_1_1_user_info.html", "struct_form_it_1_1_collaboration_1_1_user_info" ]
      ] ],
      [ "Entitlement", "namespace_form_it_1_1_entitlement.html", [
        [ "UserProfile", "class_form_it_1_1_entitlement_1_1_user_profile.html", "class_form_it_1_1_entitlement_1_1_user_profile" ]
      ] ],
      [ "Files", "namespace_form_it_1_1_files.html", [
        [ "FileOptionsList", "class_form_it_1_1_files_1_1_file_options_list.html", "class_form_it_1_1_files_1_1_file_options_list" ]
      ] ],
      [ "Forge", "namespace_form_it_1_1_forge.html", [
        [ "UI", "namespace_form_it_1_1_forge_1_1_u_i.html", [
          [ "Message", "struct_form_it_1_1_forge_1_1_u_i_1_1_message.html", "struct_form_it_1_1_forge_1_1_u_i_1_1_message" ]
        ] ],
        [ "ElementInfo", "struct_form_it_1_1_forge_1_1_element_info.html", "struct_form_it_1_1_forge_1_1_element_info" ],
        [ "ExtensionInfo", "struct_form_it_1_1_forge_1_1_extension_info.html", "struct_form_it_1_1_forge_1_1_extension_info" ],
        [ "FileData", "struct_form_it_1_1_forge_1_1_file_data.html", "struct_form_it_1_1_forge_1_1_file_data" ],
        [ "FileInfo", "struct_form_it_1_1_forge_1_1_file_info.html", "struct_form_it_1_1_forge_1_1_file_info" ],
        [ "FolderContents", "struct_form_it_1_1_forge_1_1_folder_contents.html", "struct_form_it_1_1_forge_1_1_folder_contents" ],
        [ "FolderInfo", "struct_form_it_1_1_forge_1_1_folder_info.html", null ],
        [ "HubInfo", "struct_form_it_1_1_forge_1_1_hub_info.html", "struct_form_it_1_1_forge_1_1_hub_info" ],
        [ "PermissionsInfo", "struct_form_it_1_1_forge_1_1_permissions_info.html", "struct_form_it_1_1_forge_1_1_permissions_info" ],
        [ "ProjectInfo", "struct_form_it_1_1_forge_1_1_project_info.html", "struct_form_it_1_1_forge_1_1_project_info" ],
        [ "RevitFamilyInfo", "struct_form_it_1_1_forge_1_1_revit_family_info.html", "struct_form_it_1_1_forge_1_1_revit_family_info" ]
      ] ],
      [ "Layers", "namespace_form_it_1_1_layers.html", [
        [ "LayerData", "struct_form_it_1_1_layers_1_1_layer_data.html", "struct_form_it_1_1_layers_1_1_layer_data" ]
      ] ],
      [ "Materials", "namespace_form_it_1_1_materials.html", [
        [ "MaterialData", "struct_form_it_1_1_materials_1_1_material_data.html", "struct_form_it_1_1_materials_1_1_material_data" ]
      ] ],
      [ "UI", "namespace_form_it_1_1_u_i.html", [
        [ "ShowNotificationData", "struct_form_it_1_1_u_i_1_1_show_notification_data.html", "struct_form_it_1_1_u_i_1_1_show_notification_data" ]
      ] ],
      [ "UndoManagement", "namespace_form_it_1_1_undo_management.html", [
        [ "HistoryID", "struct_form_it_1_1_undo_management_1_1_history_i_d.html", "struct_form_it_1_1_undo_management_1_1_history_i_d" ],
        [ "JSHistoryID", "class_form_it_1_1_undo_management_1_1_j_s_history_i_d.html", "class_form_it_1_1_undo_management_1_1_j_s_history_i_d" ],
        [ "JSStateID", "class_form_it_1_1_undo_management_1_1_j_s_state_i_d.html", "class_form_it_1_1_undo_management_1_1_j_s_state_i_d" ],
        [ "StateData", "struct_form_it_1_1_undo_management_1_1_state_data.html", "struct_form_it_1_1_undo_management_1_1_state_data" ],
        [ "StateID", "struct_form_it_1_1_undo_management_1_1_state_i_d.html", "struct_form_it_1_1_undo_management_1_1_state_i_d" ],
        [ "StateManager", "class_form_it_1_1_undo_management_1_1_state_manager.html", "class_form_it_1_1_undo_management_1_1_state_manager" ],
        [ "Suspend", "class_form_it_1_1_undo_management_1_1_suspend.html", "class_form_it_1_1_undo_management_1_1_suspend" ]
      ] ],
      [ "Utils", "namespace_form_it_1_1_utils.html", [
        [ "HistoryStats", "struct_form_it_1_1_utils_1_1_history_stats.html", "struct_form_it_1_1_utils_1_1_history_stats" ],
        [ "ModelStatSummary", "struct_form_it_1_1_utils_1_1_model_stat_summary.html", "struct_form_it_1_1_utils_1_1_model_stat_summary" ],
        [ "Span", "struct_form_it_1_1_utils_1_1_span.html", "struct_form_it_1_1_utils_1_1_span" ],
        [ "UtilsImage", "class_form_it_1_1_utils_1_1_utils_image.html", "class_form_it_1_1_utils_1_1_utils_image" ]
      ] ],
      [ "Web", "namespace_form_it_1_1_web.html", [
        [ "Header", "struct_form_it_1_1_web_1_1_header.html", "struct_form_it_1_1_web_1_1_header" ],
        [ "RequestConfig", "struct_form_it_1_1_web_1_1_request_config.html", "struct_form_it_1_1_web_1_1_request_config" ],
        [ "Response", "class_form_it_1_1_web_1_1_response.html", "class_form_it_1_1_web_1_1_response" ]
      ] ],
      [ "ContentDataWithoutAXM", "struct_form_it_1_1_content_data_without_a_x_m.html", "struct_form_it_1_1_content_data_without_a_x_m" ],
      [ "ImageData", "class_form_it_1_1_image_data.html", "class_form_it_1_1_image_data" ],
      [ "kAnalyticsLogType", "struct_form_it_1_1k_analytics_log_type.html", "struct_form_it_1_1k_analytics_log_type" ],
      [ "kAnimationAddedType", "struct_form_it_1_1k_animation_added_type.html", "struct_form_it_1_1k_animation_added_type" ],
      [ "kAnimationNameUpdatedType", "struct_form_it_1_1k_animation_name_updated_type.html", "struct_form_it_1_1k_animation_name_updated_type" ],
      [ "kAppUIExitType", "struct_form_it_1_1k_app_u_i_exit_type.html", "struct_form_it_1_1k_app_u_i_exit_type" ],
      [ "kAppUIInitializedType", "struct_form_it_1_1k_app_u_i_initialized_type.html", "struct_form_it_1_1k_app_u_i_initialized_type" ],
      [ "kArrayToolRequestType", "struct_form_it_1_1k_array_tool_request_type.html", "struct_form_it_1_1k_array_tool_request_type" ],
      [ "kAutoSaveRequestedType", "struct_form_it_1_1k_auto_save_requested_type.html", "struct_form_it_1_1k_auto_save_requested_type" ],
      [ "kAxesVisibilityChangedType", "struct_form_it_1_1k_axes_visibility_changed_type.html", "struct_form_it_1_1k_axes_visibility_changed_type" ],
      [ "kCameraChangedType", "struct_form_it_1_1k_camera_changed_type.html", "struct_form_it_1_1k_camera_changed_type" ],
      [ "kCameraOperationEndedType", "struct_form_it_1_1k_camera_operation_ended_type.html", "struct_form_it_1_1k_camera_operation_ended_type" ],
      [ "kCameraOperationStartedType", "struct_form_it_1_1k_camera_operation_started_type.html", "struct_form_it_1_1k_camera_operation_started_type" ],
      [ "kCameraProjectionTypeChangedType", "struct_form_it_1_1k_camera_projection_type_changed_type.html", "struct_form_it_1_1k_camera_projection_type_changed_type" ],
      [ "kCameraSharingChangeType", "struct_form_it_1_1k_camera_sharing_change_type.html", "struct_form_it_1_1k_camera_sharing_change_type" ],
      [ "kChatEmitType", "struct_form_it_1_1k_chat_emit_type.html", "struct_form_it_1_1k_chat_emit_type" ],
      [ "kChatReceivedType", "struct_form_it_1_1k_chat_received_type.html", "struct_form_it_1_1k_chat_received_type" ],
      [ "kCollabConnectionChangeType", "struct_form_it_1_1k_collab_connection_change_type.html", "struct_form_it_1_1k_collab_connection_change_type" ],
      [ "kCollaborationInitProgressUpdatedType", "struct_form_it_1_1k_collaboration_init_progress_updated_type.html", "struct_form_it_1_1k_collaboration_init_progress_updated_type" ],
      [ "kCollaborationLoadProgressUpdatedType", "struct_form_it_1_1k_collaboration_load_progress_updated_type.html", "struct_form_it_1_1k_collaboration_load_progress_updated_type" ],
      [ "kCollaborationTextType", "struct_form_it_1_1k_collaboration_text_type.html", "struct_form_it_1_1k_collaboration_text_type" ],
      [ "kCollaborationUserListUpdatedType", "struct_form_it_1_1k_collaboration_user_list_updated_type.html", "struct_form_it_1_1k_collaboration_user_list_updated_type" ],
      [ "kCollabSessionInitType", "struct_form_it_1_1k_collab_session_init_type.html", "struct_form_it_1_1k_collab_session_init_type" ],
      [ "kContentLibraryLocationsChangedType", "struct_form_it_1_1k_content_library_locations_changed_type.html", "struct_form_it_1_1k_content_library_locations_changed_type" ],
      [ "kCopyType", "struct_form_it_1_1k_copy_type.html", "struct_form_it_1_1k_copy_type" ],
      [ "kCreatePanelType", "struct_form_it_1_1k_create_panel_type.html", "struct_form_it_1_1k_create_panel_type" ],
      [ "kCreateToolbarType", "struct_form_it_1_1k_create_toolbar_type.html", "struct_form_it_1_1k_create_toolbar_type" ],
      [ "kCutType", "struct_form_it_1_1k_cut_type.html", "struct_form_it_1_1k_cut_type" ],
      [ "kDefaultColorsChangedType", "struct_form_it_1_1k_default_colors_changed_type.html", "struct_form_it_1_1k_default_colors_changed_type" ],
      [ "kDimensionGraphicsUpdateType", "struct_form_it_1_1k_dimension_graphics_update_type.html", "struct_form_it_1_1k_dimension_graphics_update_type" ],
      [ "kDismissProgressUIType", "struct_form_it_1_1k_dismiss_progress_u_i_type.html", "struct_form_it_1_1k_dismiss_progress_u_i_type" ],
      [ "kDisplayModeChangedType", "struct_form_it_1_1k_display_mode_changed_type.html", "struct_form_it_1_1k_display_mode_changed_type" ],
      [ "kDynamoFileLocationsChangedType", "struct_form_it_1_1k_dynamo_file_locations_changed_type.html", "struct_form_it_1_1k_dynamo_file_locations_changed_type" ],
      [ "kDynamoResetReachType", "struct_form_it_1_1k_dynamo_reset_reach_type.html", "struct_form_it_1_1k_dynamo_reset_reach_type" ],
      [ "kDynamoRunStateChangedType", "struct_form_it_1_1k_dynamo_run_state_changed_type.html", "struct_form_it_1_1k_dynamo_run_state_changed_type" ],
      [ "kFollowCameraType", "struct_form_it_1_1k_follow_camera_type.html", "struct_form_it_1_1k_follow_camera_type" ],
      [ "kFormItJSONMsgType", "struct_form_it_1_1k_form_it_j_s_o_n_msg_type.html", "struct_form_it_1_1k_form_it_j_s_o_n_msg_type" ],
      [ "kFYSpriteCreateType", "struct_form_it_1_1k_f_y_sprite_create_type.html", "struct_form_it_1_1k_f_y_sprite_create_type" ],
      [ "kFYSpriteDeleteType", "struct_form_it_1_1k_f_y_sprite_delete_type.html", "struct_form_it_1_1k_f_y_sprite_delete_type" ],
      [ "kFYSpriteSetPositionType", "struct_form_it_1_1k_f_y_sprite_set_position_type.html", "struct_form_it_1_1k_f_y_sprite_set_position_type" ],
      [ "kFYSpriteSetTransformType", "struct_form_it_1_1k_f_y_sprite_set_transform_type.html", "struct_form_it_1_1k_f_y_sprite_set_transform_type" ],
      [ "kFYSpriteSetVisibleType", "struct_form_it_1_1k_f_y_sprite_set_visible_type.html", "struct_form_it_1_1k_f_y_sprite_set_visible_type" ],
      [ "kGraphicsFactoryCreateMarkerType", "struct_form_it_1_1k_graphics_factory_create_marker_type.html", "struct_form_it_1_1k_graphics_factory_create_marker_type" ],
      [ "kGraphicsFactoryDeleteItemType", "struct_form_it_1_1k_graphics_factory_delete_item_type.html", "struct_form_it_1_1k_graphics_factory_delete_item_type" ],
      [ "kGraphicsFactoryMarkerSetActiveType", "struct_form_it_1_1k_graphics_factory_marker_set_active_type.html", "struct_form_it_1_1k_graphics_factory_marker_set_active_type" ],
      [ "kGraphicsFactoryMarkerSetPositionType", "struct_form_it_1_1k_graphics_factory_marker_set_position_type.html", "struct_form_it_1_1k_graphics_factory_marker_set_position_type" ],
      [ "kGraphicsFactoryMarkerSetVisibleType", "struct_form_it_1_1k_graphics_factory_marker_set_visible_type.html", "struct_form_it_1_1k_graphics_factory_marker_set_visible_type" ],
      [ "kGraphicsFactoryPolygonCreateType", "struct_form_it_1_1k_graphics_factory_polygon_create_type.html", "struct_form_it_1_1k_graphics_factory_polygon_create_type" ],
      [ "kGraphicsFactoryPolygonDeleteType", "struct_form_it_1_1k_graphics_factory_polygon_delete_type.html", "struct_form_it_1_1k_graphics_factory_polygon_delete_type" ],
      [ "kGraphicsFactoryPolygonSetMaterialNameType", "struct_form_it_1_1k_graphics_factory_polygon_set_material_name_type.html", "struct_form_it_1_1k_graphics_factory_polygon_set_material_name_type" ],
      [ "kGraphicsFactoryPolygonSetMaterialPropsType", "struct_form_it_1_1k_graphics_factory_polygon_set_material_props_type.html", "struct_form_it_1_1k_graphics_factory_polygon_set_material_props_type" ],
      [ "kGraphicsFactoryPolygonSetPositionsType", "struct_form_it_1_1k_graphics_factory_polygon_set_positions_type.html", "struct_form_it_1_1k_graphics_factory_polygon_set_positions_type" ],
      [ "kGraphicsFactoryPolygonSetTransformType", "struct_form_it_1_1k_graphics_factory_polygon_set_transform_type.html", "struct_form_it_1_1k_graphics_factory_polygon_set_transform_type" ],
      [ "kGraphicsFactoryPolygonSetVisibleType", "struct_form_it_1_1k_graphics_factory_polygon_set_visible_type.html", "struct_form_it_1_1k_graphics_factory_polygon_set_visible_type" ],
      [ "kGraphicsFactoryPolylineCreateType", "struct_form_it_1_1k_graphics_factory_polyline_create_type.html", "struct_form_it_1_1k_graphics_factory_polyline_create_type" ],
      [ "kGraphicsFactoryPolylineDeleteType", "struct_form_it_1_1k_graphics_factory_polyline_delete_type.html", "struct_form_it_1_1k_graphics_factory_polyline_delete_type" ],
      [ "kGraphicsFactoryPolylineSetPositionsType", "struct_form_it_1_1k_graphics_factory_polyline_set_positions_type.html", "struct_form_it_1_1k_graphics_factory_polyline_set_positions_type" ],
      [ "kGraphicsFactoryPolylineSetTransformType", "struct_form_it_1_1k_graphics_factory_polyline_set_transform_type.html", "struct_form_it_1_1k_graphics_factory_polyline_set_transform_type" ],
      [ "kGraphicsFactoryPolylineSetVisibleType", "struct_form_it_1_1k_graphics_factory_polyline_set_visible_type.html", "struct_form_it_1_1k_graphics_factory_polyline_set_visible_type" ],
      [ "kGridScaleChangedType", "struct_form_it_1_1k_grid_scale_changed_type.html", "struct_form_it_1_1k_grid_scale_changed_type" ],
      [ "kHistoryDeletedForModelTreeOnlyType", "struct_form_it_1_1k_history_deleted_for_model_tree_only_type.html", "struct_form_it_1_1k_history_deleted_for_model_tree_only_type" ],
      [ "kHUDMessageType", "struct_form_it_1_1k_h_u_d_message_type.html", "struct_form_it_1_1k_h_u_d_message_type" ],
      [ "kImageAddedType", "struct_form_it_1_1k_image_added_type.html", "struct_form_it_1_1k_image_added_type" ],
      [ "kImageAlphaChangedType", "struct_form_it_1_1k_image_alpha_changed_type.html", "struct_form_it_1_1k_image_alpha_changed_type" ],
      [ "kImageChangedType", "struct_form_it_1_1k_image_changed_type.html", "struct_form_it_1_1k_image_changed_type" ],
      [ "kImageDeletedType", "struct_form_it_1_1k_image_deleted_type.html", "struct_form_it_1_1k_image_deleted_type" ],
      [ "kImageOrderChangedType", "struct_form_it_1_1k_image_order_changed_type.html", "struct_form_it_1_1k_image_order_changed_type" ],
      [ "kInContextEditingType", "struct_form_it_1_1k_in_context_editing_type.html", "struct_form_it_1_1k_in_context_editing_type" ],
      [ "kInferenceEventIgnoreObjectChangedType", "struct_form_it_1_1k_inference_event_ignore_object_changed_type.html", "struct_form_it_1_1k_inference_event_ignore_object_changed_type" ],
      [ "kInferenceEventInferenceLockedChangedType", "struct_form_it_1_1k_inference_event_inference_locked_changed_type.html", "struct_form_it_1_1k_inference_event_inference_locked_changed_type" ],
      [ "kInstallPluginType", "struct_form_it_1_1k_install_plugin_type.html", "struct_form_it_1_1k_install_plugin_type" ],
      [ "kInvalidateEdgesType", "struct_form_it_1_1k_invalidate_edges_type.html", "struct_form_it_1_1k_invalidate_edges_type" ],
      [ "kInvalidatePreviewImageType", "struct_form_it_1_1k_invalidate_preview_image_type.html", "struct_form_it_1_1k_invalidate_preview_image_type" ],
      [ "kLayerLoadInRevitChangedType", "struct_form_it_1_1k_layer_load_in_revit_changed_type.html", "struct_form_it_1_1k_layer_load_in_revit_changed_type" ],
      [ "kLayerManagerChangedType", "struct_form_it_1_1k_layer_manager_changed_type.html", "struct_form_it_1_1k_layer_manager_changed_type" ],
      [ "kLayerNameChangedType", "struct_form_it_1_1k_layer_name_changed_type.html", "struct_form_it_1_1k_layer_name_changed_type" ],
      [ "kLayerPickableChangedType", "struct_form_it_1_1k_layer_pickable_changed_type.html", "struct_form_it_1_1k_layer_pickable_changed_type" ],
      [ "kLayerVisibilityChangedType", "struct_form_it_1_1k_layer_visibility_changed_type.html", "struct_form_it_1_1k_layer_visibility_changed_type" ],
      [ "kLCSChangedType", "struct_form_it_1_1k_l_c_s_changed_type.html", "struct_form_it_1_1k_l_c_s_changed_type" ],
      [ "kLevelManagerChangedType", "struct_form_it_1_1k_level_manager_changed_type.html", "struct_form_it_1_1k_level_manager_changed_type" ],
      [ "kLevelsVisibilityChangedType", "struct_form_it_1_1k_levels_visibility_changed_type.html", "struct_form_it_1_1k_levels_visibility_changed_type" ],
      [ "kLoadCompleteType", "struct_form_it_1_1k_load_complete_type.html", "struct_form_it_1_1k_load_complete_type" ],
      [ "kLockAndHidePointerType", "struct_form_it_1_1k_lock_and_hide_pointer_type.html", "struct_form_it_1_1k_lock_and_hide_pointer_type" ],
      [ "kMaterialAddedType", "struct_form_it_1_1k_material_added_type.html", "struct_form_it_1_1k_material_added_type" ],
      [ "kMaterialChangedType", "struct_form_it_1_1k_material_changed_type.html", "struct_form_it_1_1k_material_changed_type" ],
      [ "kMaterialCreatedFromSampleType", "struct_form_it_1_1k_material_created_from_sample_type.html", "struct_form_it_1_1k_material_created_from_sample_type" ],
      [ "kMaterialDataChangedType", "struct_form_it_1_1k_material_data_changed_type.html", "struct_form_it_1_1k_material_data_changed_type" ],
      [ "kMaterialDeletedType", "struct_form_it_1_1k_material_deleted_type.html", "struct_form_it_1_1k_material_deleted_type" ],
      [ "kMaterialManagerChangedType", "struct_form_it_1_1k_material_manager_changed_type.html", "struct_form_it_1_1k_material_manager_changed_type" ],
      [ "kMaterialPickedType", "struct_form_it_1_1k_material_picked_type.html", "struct_form_it_1_1k_material_picked_type" ],
      [ "kModelChangedType", "struct_form_it_1_1k_model_changed_type.html", "struct_form_it_1_1k_model_changed_type" ],
      [ "kNewModelRequestedType", "struct_form_it_1_1k_new_model_requested_type.html", "struct_form_it_1_1k_new_model_requested_type" ],
      [ "kObjectFacetingAccuracyChangedType", "struct_form_it_1_1k_object_faceting_accuracy_changed_type.html", "struct_form_it_1_1k_object_faceting_accuracy_changed_type" ],
      [ "kObjectsPreselectType", "struct_form_it_1_1k_objects_preselect_type.html", "struct_form_it_1_1k_objects_preselect_type" ],
      [ "kOpenFileCompleteType", "struct_form_it_1_1k_open_file_complete_type.html", "struct_form_it_1_1k_open_file_complete_type" ],
      [ "kOpenFileStartedType", "struct_form_it_1_1k_open_file_started_type.html", "struct_form_it_1_1k_open_file_started_type" ],
      [ "kOxygenAuthenticationStatusChangedType", "struct_form_it_1_1k_oxygen_authentication_status_changed_type.html", "struct_form_it_1_1k_oxygen_authentication_status_changed_type" ],
      [ "kPanoramInProgressType", "struct_form_it_1_1k_panoram_in_progress_type.html", "struct_form_it_1_1k_panoram_in_progress_type" ],
      [ "kPasteInPlaceType", "struct_form_it_1_1k_paste_in_place_type.html", "struct_form_it_1_1k_paste_in_place_type" ],
      [ "kPasteType", "struct_form_it_1_1k_paste_type.html", "struct_form_it_1_1k_paste_type" ],
      [ "kPlacementToolTransformType", "struct_form_it_1_1k_placement_tool_transform_type.html", "struct_form_it_1_1k_placement_tool_transform_type" ],
      [ "kPostProgressUpdateType", "struct_form_it_1_1k_post_progress_update_type.html", "struct_form_it_1_1k_post_progress_update_type" ],
      [ "kPresentProgressUIType", "struct_form_it_1_1k_present_progress_u_i_type.html", "struct_form_it_1_1k_present_progress_u_i_type" ],
      [ "kPrimitiveCreationToolFinishType", "struct_form_it_1_1k_primitive_creation_tool_finish_type.html", "struct_form_it_1_1k_primitive_creation_tool_finish_type" ],
      [ "kPrimitiveCreationToolInitType", "struct_form_it_1_1k_primitive_creation_tool_init_type.html", "struct_form_it_1_1k_primitive_creation_tool_init_type" ],
      [ "kProjectNameUpdatedType", "struct_form_it_1_1k_project_name_updated_type.html", "struct_form_it_1_1k_project_name_updated_type" ],
      [ "kProjectPropertiesChangedType", "struct_form_it_1_1k_project_properties_changed_type.html", "struct_form_it_1_1k_project_properties_changed_type" ],
      [ "kRefresh3DViewType", "struct_form_it_1_1k_refresh3_d_view_type.html", "struct_form_it_1_1k_refresh3_d_view_type" ],
      [ "kReset3DViewportType", "struct_form_it_1_1k_reset3_d_viewport_type.html", "struct_form_it_1_1k_reset3_d_viewport_type" ],
      [ "kReSize3DViewType", "struct_form_it_1_1k_re_size3_d_view_type.html", "struct_form_it_1_1k_re_size3_d_view_type" ],
      [ "kRevitConnectionChangeType", "struct_form_it_1_1k_revit_connection_change_type.html", "struct_form_it_1_1k_revit_connection_change_type" ],
      [ "kRevitFamilyInfoChangedType", "struct_form_it_1_1k_revit_family_info_changed_type.html", "struct_form_it_1_1k_revit_family_info_changed_type" ],
      [ "kSampleMaterialsLocationsChangedType", "struct_form_it_1_1k_sample_materials_locations_changed_type.html", "struct_form_it_1_1k_sample_materials_locations_changed_type" ],
      [ "kSampleMaterialsNodeLoadedType", "struct_form_it_1_1k_sample_materials_node_loaded_type.html", "struct_form_it_1_1k_sample_materials_node_loaded_type" ],
      [ "kSampleMaterialsNodeLoadFailedType", "struct_form_it_1_1k_sample_materials_node_load_failed_type.html", "struct_form_it_1_1k_sample_materials_node_load_failed_type" ],
      [ "kSampleMaterialsNodeLoadingStatusChangedType", "struct_form_it_1_1k_sample_materials_node_loading_status_changed_type.html", "struct_form_it_1_1k_sample_materials_node_loading_status_changed_type" ],
      [ "kSatelliteImageIsHiddenType", "struct_form_it_1_1k_satellite_image_is_hidden_type.html", "struct_form_it_1_1k_satellite_image_is_hidden_type" ],
      [ "kSatelliteImageIsVisibleType", "struct_form_it_1_1k_satellite_image_is_visible_type.html", "struct_form_it_1_1k_satellite_image_is_visible_type" ],
      [ "kSaveCompletedType", "struct_form_it_1_1k_save_completed_type.html", "struct_form_it_1_1k_save_completed_type" ],
      [ "kSaveLocallyRequestedType", "struct_form_it_1_1k_save_locally_requested_type.html", "struct_form_it_1_1k_save_locally_requested_type" ],
      [ "kSaveLocallyWithHistoryRequestedType", "struct_form_it_1_1k_save_locally_with_history_requested_type.html", "struct_form_it_1_1k_save_locally_with_history_requested_type" ],
      [ "kSaveRequestedType", "struct_form_it_1_1k_save_requested_type.html", "struct_form_it_1_1k_save_requested_type" ],
      [ "kSceneActivatedType", "struct_form_it_1_1k_scene_activated_type.html", "struct_form_it_1_1k_scene_activated_type" ],
      [ "kSceneAddedType", "struct_form_it_1_1k_scene_added_type.html", "struct_form_it_1_1k_scene_added_type" ],
      [ "kSceneCameraChangedType", "struct_form_it_1_1k_scene_camera_changed_type.html", "struct_form_it_1_1k_scene_camera_changed_type" ],
      [ "kSceneItemChangedType", "struct_form_it_1_1k_scene_item_changed_type.html", "struct_form_it_1_1k_scene_item_changed_type" ],
      [ "kSceneModifiedStateChangedType", "struct_form_it_1_1k_scene_modified_state_changed_type.html", "struct_form_it_1_1k_scene_modified_state_changed_type" ],
      [ "kSceneNameUpdatedType", "struct_form_it_1_1k_scene_name_updated_type.html", "struct_form_it_1_1k_scene_name_updated_type" ],
      [ "kSceneRemovedType", "struct_form_it_1_1k_scene_removed_type.html", "struct_form_it_1_1k_scene_removed_type" ],
      [ "kScenesAnimationStartStopType", "struct_form_it_1_1k_scenes_animation_start_stop_type.html", "struct_form_it_1_1k_scenes_animation_start_stop_type" ],
      [ "kScenesRecordEndType", "struct_form_it_1_1k_scenes_record_end_type.html", "struct_form_it_1_1k_scenes_record_end_type" ],
      [ "kScenesRecordFrameType", "struct_form_it_1_1k_scenes_record_frame_type.html", "struct_form_it_1_1k_scenes_record_frame_type" ],
      [ "kScenesRecordStartType", "struct_form_it_1_1k_scenes_record_start_type.html", "struct_form_it_1_1k_scenes_record_start_type" ],
      [ "kScenesUpdatedType", "struct_form_it_1_1k_scenes_updated_type.html", "struct_form_it_1_1k_scenes_updated_type" ],
      [ "kSceneUpdatedType", "struct_form_it_1_1k_scene_updated_type.html", "struct_form_it_1_1k_scene_updated_type" ],
      [ "kSelectionFilterChangedType", "struct_form_it_1_1k_selection_filter_changed_type.html", "struct_form_it_1_1k_selection_filter_changed_type" ],
      [ "kSelectionHightlightEnabledChangedType", "struct_form_it_1_1k_selection_hightlight_enabled_changed_type.html", "struct_form_it_1_1k_selection_hightlight_enabled_changed_type" ],
      [ "kSelectionsChangedType", "struct_form_it_1_1k_selections_changed_type.html", "struct_form_it_1_1k_selections_changed_type" ],
      [ "kSendToRevitPreviewChangedType", "struct_form_it_1_1k_send_to_revit_preview_changed_type.html", "struct_form_it_1_1k_send_to_revit_preview_changed_type" ],
      [ "kSetCursorType", "struct_form_it_1_1k_set_cursor_type.html", "struct_form_it_1_1k_set_cursor_type" ],
      [ "kSetLocationType", "struct_form_it_1_1k_set_location_type.html", "struct_form_it_1_1k_set_location_type" ],
      [ "kSetToolTypeCursorType", "struct_form_it_1_1k_set_tool_type_cursor_type.html", "struct_form_it_1_1k_set_tool_type_cursor_type" ],
      [ "kShowDimensionEditorType", "struct_form_it_1_1k_show_dimension_editor_type.html", "struct_form_it_1_1k_show_dimension_editor_type" ],
      [ "kShowDimensionSettingChangedType", "struct_form_it_1_1k_show_dimension_setting_changed_type.html", "struct_form_it_1_1k_show_dimension_setting_changed_type" ],
      [ "kShowEditedGroupOnlyChangedType", "struct_form_it_1_1k_show_edited_group_only_changed_type.html", "struct_form_it_1_1k_show_edited_group_only_changed_type" ],
      [ "kShowTooltipType", "struct_form_it_1_1k_show_tooltip_type.html", "struct_form_it_1_1k_show_tooltip_type" ],
      [ "kSolarAnalysisFinishedRunType", "struct_form_it_1_1k_solar_analysis_finished_run_type.html", "struct_form_it_1_1k_solar_analysis_finished_run_type" ],
      [ "kSolarAnalysisModeChangedType", "struct_form_it_1_1k_solar_analysis_mode_changed_type.html", "struct_form_it_1_1k_solar_analysis_mode_changed_type" ],
      [ "kSolarAnalysisPeakMonthChangedType", "struct_form_it_1_1k_solar_analysis_peak_month_changed_type.html", "struct_form_it_1_1k_solar_analysis_peak_month_changed_type" ],
      [ "kSolarAnalysisResultTypeChangedType", "struct_form_it_1_1k_solar_analysis_result_type_changed_type.html", "struct_form_it_1_1k_solar_analysis_result_type_changed_type" ],
      [ "kSolarAnalysisSelectionHighlightType", "struct_form_it_1_1k_solar_analysis_selection_highlight_type.html", "struct_form_it_1_1k_solar_analysis_selection_highlight_type" ],
      [ "kSolarAnalysisWeatherDataNotAvailableType", "struct_form_it_1_1k_solar_analysis_weather_data_not_available_type.html", "struct_form_it_1_1k_solar_analysis_weather_data_not_available_type" ],
      [ "kStartUIToolType", "struct_form_it_1_1k_start_u_i_tool_type.html", "struct_form_it_1_1k_start_u_i_tool_type" ],
      [ "kSunDirectionChangedType", "struct_form_it_1_1k_sun_direction_changed_type.html", "struct_form_it_1_1k_sun_direction_changed_type" ],
      [ "kSunDirectionChangesEndedType", "struct_form_it_1_1k_sun_direction_changes_ended_type.html", "struct_form_it_1_1k_sun_direction_changes_ended_type" ],
      [ "kTempRendererCreateType", "struct_form_it_1_1k_temp_renderer_create_type.html", "struct_form_it_1_1k_temp_renderer_create_type" ],
      [ "kTempRendererDestroyType", "struct_form_it_1_1k_temp_renderer_destroy_type.html", "struct_form_it_1_1k_temp_renderer_destroy_type" ],
      [ "kTempRendererUpdateType", "struct_form_it_1_1k_temp_renderer_update_type.html", "struct_form_it_1_1k_temp_renderer_update_type" ],
      [ "kTestRunningType", "struct_form_it_1_1k_test_running_type.html", "struct_form_it_1_1k_test_running_type" ],
      [ "kTimerTickedType", "struct_form_it_1_1k_timer_ticked_type.html", "struct_form_it_1_1k_timer_ticked_type" ],
      [ "kToggleAllPalettesVisibilityRequestedType", "struct_form_it_1_1k_toggle_all_palettes_visibility_requested_type.html", "struct_form_it_1_1k_toggle_all_palettes_visibility_requested_type" ],
      [ "kToolDimensionDeleteType", "struct_form_it_1_1k_tool_dimension_delete_type.html", "struct_form_it_1_1k_tool_dimension_delete_type" ],
      [ "kToolDimensionInitType", "struct_form_it_1_1k_tool_dimension_init_type.html", "struct_form_it_1_1k_tool_dimension_init_type" ],
      [ "kToolDimensionSetEnabledType", "struct_form_it_1_1k_tool_dimension_set_enabled_type.html", "struct_form_it_1_1k_tool_dimension_set_enabled_type" ],
      [ "kToolDimensionSetPointsType", "struct_form_it_1_1k_tool_dimension_set_points_type.html", "struct_form_it_1_1k_tool_dimension_set_points_type" ],
      [ "kToolDimensionUpdateAngularType", "struct_form_it_1_1k_tool_dimension_update_angular_type.html", "struct_form_it_1_1k_tool_dimension_update_angular_type" ],
      [ "kToolDimensionUpdateLinearType", "struct_form_it_1_1k_tool_dimension_update_linear_type.html", "struct_form_it_1_1k_tool_dimension_update_linear_type" ],
      [ "kToolDimensionUpdateScalarType", "struct_form_it_1_1k_tool_dimension_update_scalar_type.html", "struct_form_it_1_1k_tool_dimension_update_scalar_type" ],
      [ "kToolFeatureFlagChangedType", "struct_form_it_1_1k_tool_feature_flag_changed_type.html", "struct_form_it_1_1k_tool_feature_flag_changed_type" ],
      [ "kToolGotFocusType", "struct_form_it_1_1k_tool_got_focus_type.html", "struct_form_it_1_1k_tool_got_focus_type" ],
      [ "kToolHandledType", "struct_form_it_1_1k_tool_handled_type.html", "struct_form_it_1_1k_tool_handled_type" ],
      [ "kToolModeChangedType", "struct_form_it_1_1k_tool_mode_changed_type.html", "struct_form_it_1_1k_tool_mode_changed_type" ],
      [ "kToolRemovedType", "struct_form_it_1_1k_tool_removed_type.html", "struct_form_it_1_1k_tool_removed_type" ],
      [ "kToolsLocationRequestType", "struct_form_it_1_1k_tools_location_request_type.html", "struct_form_it_1_1k_tools_location_request_type" ],
      [ "kTouchEnabledChangedType", "struct_form_it_1_1k_touch_enabled_changed_type.html", "struct_form_it_1_1k_touch_enabled_changed_type" ],
      [ "kUndoManagerDeleteAllRedoType", "struct_form_it_1_1k_undo_manager_delete_all_redo_type.html", "struct_form_it_1_1k_undo_manager_delete_all_redo_type" ],
      [ "kUndoManagerStateAddedType", "struct_form_it_1_1k_undo_manager_state_added_type.html", "struct_form_it_1_1k_undo_manager_state_added_type" ],
      [ "kUndoManagerStateNameChangeType", "struct_form_it_1_1k_undo_manager_state_name_change_type.html", "struct_form_it_1_1k_undo_manager_state_name_change_type" ],
      [ "kUndoManagerUpdateType", "struct_form_it_1_1k_undo_manager_update_type.html", "struct_form_it_1_1k_undo_manager_update_type" ],
      [ "kUndoRedoAvailabilityChangedType", "struct_form_it_1_1k_undo_redo_availability_changed_type.html", "struct_form_it_1_1k_undo_redo_availability_changed_type" ],
      [ "kUndoRedoExecutedType", "struct_form_it_1_1k_undo_redo_executed_type.html", "struct_form_it_1_1k_undo_redo_executed_type" ],
      [ "kUndoRedoPerHistoryType", "struct_form_it_1_1k_undo_redo_per_history_type.html", "struct_form_it_1_1k_undo_redo_per_history_type" ],
      [ "kUnfollowCameraType", "struct_form_it_1_1k_unfollow_camera_type.html", "struct_form_it_1_1k_unfollow_camera_type" ],
      [ "kUninstallPluginType", "struct_form_it_1_1k_uninstall_plugin_type.html", "struct_form_it_1_1k_uninstall_plugin_type" ],
      [ "kUnitTypeChangedType", "struct_form_it_1_1k_unit_type_changed_type.html", "struct_form_it_1_1k_unit_type_changed_type" ],
      [ "kUpdateRenderHistoryType", "struct_form_it_1_1k_update_render_history_type.html", "struct_form_it_1_1k_update_render_history_type" ],
      [ "kUserEntitlementsChangedType", "struct_form_it_1_1k_user_entitlements_changed_type.html", "struct_form_it_1_1k_user_entitlements_changed_type" ],
      [ "kVisualStyleChangedType", "struct_form_it_1_1k_visual_style_changed_type.html", "struct_form_it_1_1k_visual_style_changed_type" ],
      [ "LevelData", "class_form_it_1_1_level_data.html", "class_form_it_1_1_level_data" ],
      [ "LoadCompleteData", "struct_form_it_1_1_load_complete_data.html", "struct_form_it_1_1_load_complete_data" ],
      [ "MaterialManagerChangedData", "struct_form_it_1_1_material_manager_changed_data.html", "struct_form_it_1_1_material_manager_changed_data" ],
      [ "MessageBroadcaster", "class_form_it_1_1_message_broadcaster.html", null ],
      [ "MessageListener", "class_form_it_1_1_message_listener.html", "class_form_it_1_1_message_listener" ],
      [ "MessagePayloadStruct", "struct_form_it_1_1_message_payload_struct.html", "struct_form_it_1_1_message_payload_struct" ],
      [ "MessageStruct", "struct_form_it_1_1_message_struct.html", "struct_form_it_1_1_message_struct" ],
      [ "MessageVoidStruct", "struct_form_it_1_1_message_void_struct.html", null ],
      [ "MessageWithPayloadStruct", "struct_form_it_1_1_message_with_payload_struct.html", "struct_form_it_1_1_message_with_payload_struct" ],
      [ "ModelMetadata", "struct_form_it_1_1_model_metadata.html", "struct_form_it_1_1_model_metadata" ],
      [ "NotificationHandleType", "struct_form_it_1_1_notification_handle_type.html", "struct_form_it_1_1_notification_handle_type" ],
      [ "RendererData", "class_form_it_1_1_renderer_data.html", "class_form_it_1_1_renderer_data" ],
      [ "RevitFamilyInformation", "struct_form_it_1_1_revit_family_information.html", "struct_form_it_1_1_revit_family_information" ],
      [ "SaveInformation", "struct_form_it_1_1_save_information.html", "struct_form_it_1_1_save_information" ],
      [ "SelectedProperties", "struct_form_it_1_1_selected_properties.html", "struct_form_it_1_1_selected_properties" ],
      [ "SolsticeEquinoxData", "struct_form_it_1_1_solstice_equinox_data.html", "struct_form_it_1_1_solstice_equinox_data" ],
      [ "SunLocationData", "class_form_it_1_1_sun_location_data.html", "class_form_it_1_1_sun_location_data" ],
      [ "SunRiseData", "class_form_it_1_1_sun_rise_data.html", "class_form_it_1_1_sun_rise_data" ],
      [ "UTCData", "struct_form_it_1_1_u_t_c_data.html", "struct_form_it_1_1_u_t_c_data" ],
      [ "Version", "struct_form_it_1_1_version.html", "struct_form_it_1_1_version" ]
    ] ],
    [ "WSM", "namespace_w_s_m.html", [
      [ "Utils", "namespace_w_s_m_1_1_utils.html", [
        [ "CameraData", "class_w_s_m_1_1_utils_1_1_camera_data.html", "class_w_s_m_1_1_utils_1_1_camera_data" ],
        [ "HistoryBoundsHelper", "class_w_s_m_1_1_utils_1_1_history_bounds_helper.html", "class_w_s_m_1_1_utils_1_1_history_bounds_helper" ],
        [ "HistoryObjects", "class_w_s_m_1_1_utils_1_1_history_objects.html", "class_w_s_m_1_1_utils_1_1_history_objects" ],
        [ "IAppHelper", "class_w_s_m_1_1_utils_1_1_i_app_helper.html", "class_w_s_m_1_1_utils_1_1_i_app_helper" ],
        [ "IAppHelperDebug", "class_w_s_m_1_1_utils_1_1_i_app_helper_debug.html", "class_w_s_m_1_1_utils_1_1_i_app_helper_debug" ],
        [ "ICamera", "class_w_s_m_1_1_utils_1_1_i_camera.html", "class_w_s_m_1_1_utils_1_1_i_camera" ],
        [ "ITooltipProvider", "class_w_s_m_1_1_utils_1_1_i_tooltip_provider.html", "class_w_s_m_1_1_utils_1_1_i_tooltip_provider" ],
        [ "MaterialData", "class_w_s_m_1_1_utils_1_1_material_data.html", "class_w_s_m_1_1_utils_1_1_material_data" ],
        [ "MeshData", "class_w_s_m_1_1_utils_1_1_mesh_data.html", "class_w_s_m_1_1_utils_1_1_mesh_data" ],
        [ "MeshesAndTransformsData", "class_w_s_m_1_1_utils_1_1_meshes_and_transforms_data.html", "class_w_s_m_1_1_utils_1_1_meshes_and_transforms_data" ],
        [ "ObjectTypeFilter", "struct_w_s_m_1_1_utils_1_1_object_type_filter.html", "struct_w_s_m_1_1_utils_1_1_object_type_filter" ],
        [ "PickRay", "class_w_s_m_1_1_utils_1_1_pick_ray.html", "class_w_s_m_1_1_utils_1_1_pick_ray" ],
        [ "RayFireFilterHidden", "class_w_s_m_1_1_utils_1_1_ray_fire_filter_hidden.html", "class_w_s_m_1_1_utils_1_1_ray_fire_filter_hidden" ],
        [ "RayFireFilterHiddenOrNonPickable", "class_w_s_m_1_1_utils_1_1_ray_fire_filter_hidden_or_non_pickable.html", "class_w_s_m_1_1_utils_1_1_ray_fire_filter_hidden_or_non_pickable" ],
        [ "RayFireFilterHiddenOrSectioned", "class_w_s_m_1_1_utils_1_1_ray_fire_filter_hidden_or_sectioned.html", "class_w_s_m_1_1_utils_1_1_ray_fire_filter_hidden_or_sectioned" ]
      ] ],
      [ "AbstractLockGuard", "class_w_s_m_1_1_abstract_lock_guard.html", "class_w_s_m_1_1_abstract_lock_guard" ],
      [ "ATFCameraData", "struct_w_s_m_1_1_a_t_f_camera_data.html", "struct_w_s_m_1_1_a_t_f_camera_data" ],
      [ "Color", "class_w_s_m_1_1_color.html", "class_w_s_m_1_1_color" ],
      [ "CurveData", "struct_w_s_m_1_1_curve_data.html", "struct_w_s_m_1_1_curve_data" ],
      [ "EdgeData", "struct_w_s_m_1_1_edge_data.html", "struct_w_s_m_1_1_edge_data" ],
      [ "FaceData", "struct_w_s_m_1_1_face_data.html", "struct_w_s_m_1_1_face_data" ],
      [ "FacetsBodyData", "struct_w_s_m_1_1_facets_body_data.html", "struct_w_s_m_1_1_facets_body_data" ],
      [ "GroupInstancePath", "class_w_s_m_1_1_group_instance_path.html", "class_w_s_m_1_1_group_instance_path" ],
      [ "IGraphicsFactory", "class_w_s_m_1_1_i_graphics_factory.html", "class_w_s_m_1_1_i_graphics_factory" ],
      [ "ImageData", "struct_w_s_m_1_1_image_data.html", "struct_w_s_m_1_1_image_data" ],
      [ "IMarker", "class_w_s_m_1_1_i_marker.html", "class_w_s_m_1_1_i_marker" ],
      [ "InstanceData", "struct_w_s_m_1_1_instance_data.html", "struct_w_s_m_1_1_instance_data" ],
      [ "Interval2d", "class_w_s_m_1_1_interval2d.html", "class_w_s_m_1_1_interval2d" ],
      [ "Interval3d", "class_w_s_m_1_1_interval3d.html", "class_w_s_m_1_1_interval3d" ],
      [ "IPolygon", "class_w_s_m_1_1_i_polygon.html", "class_w_s_m_1_1_i_polygon" ],
      [ "IPolyLine", "class_w_s_m_1_1_i_poly_line.html", "class_w_s_m_1_1_i_poly_line" ],
      [ "IRayFireFilterAndAbort", "class_w_s_m_1_1_i_ray_fire_filter_and_abort.html", "class_w_s_m_1_1_i_ray_fire_filter_and_abort" ],
      [ "LayerData", "struct_w_s_m_1_1_layer_data.html", "struct_w_s_m_1_1_layer_data" ],
      [ "Line3d", "class_w_s_m_1_1_line3d.html", "class_w_s_m_1_1_line3d" ],
      [ "LoopData", "struct_w_s_m_1_1_loop_data.html", "struct_w_s_m_1_1_loop_data" ],
      [ "MaterialData", "struct_w_s_m_1_1_material_data.html", "struct_w_s_m_1_1_material_data" ],
      [ "MaterialProps", "class_w_s_m_1_1_material_props.html", "class_w_s_m_1_1_material_props" ],
      [ "ModelChangeData", "struct_w_s_m_1_1_model_change_data.html", "struct_w_s_m_1_1_model_change_data" ],
      [ "ObjectHistoryID", "class_w_s_m_1_1_object_history_i_d.html", "class_w_s_m_1_1_object_history_i_d" ],
      [ "Plane", "class_w_s_m_1_1_plane.html", "class_w_s_m_1_1_plane" ],
      [ "Point2d", "class_w_s_m_1_1_point2d.html", "class_w_s_m_1_1_point2d" ],
      [ "Point3d", "class_w_s_m_1_1_point3d.html", "class_w_s_m_1_1_point3d" ],
      [ "Quaternion3d", "class_w_s_m_1_1_quaternion3d.html", "class_w_s_m_1_1_quaternion3d" ],
      [ "Result", "class_w_s_m_1_1_result.html", "class_w_s_m_1_1_result" ],
      [ "TextureData", "struct_w_s_m_1_1_texture_data.html", "struct_w_s_m_1_1_texture_data" ],
      [ "Transf3d", "class_w_s_m_1_1_transf3d.html", "class_w_s_m_1_1_transf3d" ],
      [ "UnitVector3d", "class_w_s_m_1_1_unit_vector3d.html", "class_w_s_m_1_1_unit_vector3d" ],
      [ "Vector2d", "class_w_s_m_1_1_vector2d.html", "class_w_s_m_1_1_vector2d" ],
      [ "Vector3d", "class_w_s_m_1_1_vector3d.html", "class_w_s_m_1_1_vector3d" ]
    ] ]
];